<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorSqlite.Samples.Data\BlazorSqlite.Samples.Data.csproj" />
    <ProjectReference Include="..\..\src\BlazorSqlite.EntityFrameworkCore\BlazorSqlite.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\BlazorSqlite.Interop\BlazorSqlite.Interop.csproj" />
    <ProjectReference Include="..\..\src\BlazorSqlite.Js\BlazorSqlite.Js.csproj" />
    <ProjectReference Include="..\..\src\BlazorSqlite.Storage.CacheStorage\BlazorSqlite.Storage.CacheStorage.csproj" />
    <ProjectReference Include="..\..\src\BlazorSqlite.Storage.InMemory\BlazorSqlite.Storage.InMemory.csproj" />
    <ProjectReference Include="..\..\src\BlazorSqlite.Storage.IndexedDb\BlazorSqlite.Storage.IndexedDb.csproj" />
    <ProjectReference Include="..\..\src\BlazorSqlite.Storage.Opfs\BlazorSqlite.Storage.Opfs.csproj" />
  </ItemGroup>

</Project>
